// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2I-PixHyrVSlC3x_wGHwdb2Q3ItB21ak',
    appId: '1:765944913521:web:c9141797df8924397785d0',
    messagingSenderId: '765944913521',
    projectId: 'atikshop-f0e73',
    authDomain: 'atikshop-f0e73.firebaseapp.com',
    storageBucket: 'atikshop-f0e73.firebasestorage.app',
    measurementId: 'G-QW8RPX9RDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyActLZL02iSzBMOnb_W2euf7qQ6TYuMjGE',
    appId: '1:765944913521:android:42e391ad35fe75787785d0',
    messagingSenderId: '765944913521',
    projectId: 'atikshop-f0e73',
    storageBucket: 'atikshop-f0e73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMChpAXtlNKHadPxYo9JTvo_hfVnOXQEg',
    appId: '1:765944913521:ios:0885f84435e69c907785d0',
    messagingSenderId: '765944913521',
    projectId: 'atikshop-f0e73',
    storageBucket: 'atikshop-f0e73.firebasestorage.app',
    iosBundleId: 'com.atiksdev.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMChpAXtlNKHadPxYo9JTvo_hfVnOXQEg',
    appId: '1:765944913521:ios:0885f84435e69c907785d0',
    messagingSenderId: '765944913521',
    projectId: 'atikshop-f0e73',
    storageBucket: 'atikshop-f0e73.firebasestorage.app',
    iosBundleId: 'com.atiksdev.store',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2I-PixHyrVSlC3x_wGHwdb2Q3ItB21ak',
    appId: '1:765944913521:web:89df7be273de602e7785d0',
    messagingSenderId: '765944913521',
    projectId: 'atikshop-f0e73',
    authDomain: 'atikshop-f0e73.firebaseapp.com',
    storageBucket: 'atikshop-f0e73.firebasestorage.app',
    measurementId: 'G-1DNJYMXBET',
  );

}